### ISSUE TITLE
adjust Prodigy recipe to include new configs

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/ppa-nlp#68]
- [x] character versus token level highlighting
- [x] settings so that each page is annotated by two and only two annotators
- [x] ignore button (tracked as #60)

We'll have to decide what settings in the recipe versus environment.

For testing:
- [x] verify that character highlighting works as desired
- [x] verify that ignore button is no longer shown
- [x] verify that a page is only shown to two annotators (sessions); if more occur this could be a case of work stealing which can be verified in the logs

**Comment by mnaydan** [comment]
The character-level highlighting and ignore button issues look good. But as far as I can tell from the test sessions, it's still serving out everything to everyone. Even after annotations are saved/submitted in two sessions, the other test sessions receive those same pages.

**Comment by laurejt** [comment]
For task routing to work properly when we want more than one annotation per task (i.e. page), we need to specify the session names up front. The distribution of annotations will only be approximately even (routing relies on mods of hashes). Work stealing has the potential to make this more uneven, since tasks can be "stolen" from one session and reassigned to another based on the relative age of the assignment. While this can make the work distribution more uneven, it will let us finish faster.  For more on work stealing, see the [answer](https://support.prodi.gy/t/how-does-work-stealing-work/7402/2) I received from the Prodigy support forum.

For the future annotations rounds and efforts, I'm investigating how we might guarantee 2 or more annotations per task without specifying session names. We can probably achieve this by writing a custom task router routine. That said, I've made a [post](https://support.prodi.gy/t/tasking-routing-ensuring-n-annotations-without-specifying-sessions-upfront/7403) asking Prodigy support on any recommendations for how to proceed.
